apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mealie-deploy
  name: mealie-deploy
  namespace: kingsam-namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mealie-deploy
  template:
    metadata:
      labels:
        app: mealie-deploy
    spec:
      containers:
      - image: ghcr.io/mealie-recipes/mealie:v2.8.0
        name: mealie
        ports:
          - containerPort: 9000
