apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: rollingdeploy
  name: rollingdeploy
spec:
  replicas: 10
  selector:
    matchLabels:
      app: rollingdeploy
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 10%
      maxSurge: 25%
  template:
    metadata:
      labels:
        app: rollingdeploy
    spec:
      containers:
      - image: httpd:latest
        name: httpd
